name: Newman Run

on:
  push:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: petstore.collection.json 
          reporters: '["emojitrain","json"]'
          # reporter : '{ html : { export : "./htmlResults.html", template: "./customTemplate.hbs" } }'
          delayRequest: 5000
         